### PR TITLE
Replace touch command with go functions

### LINKED ISSUE #32: kubelogin fails to properly create it's config file on windows
`kubelogin config --alias=xxx --server-url=https://xxx --kubectl-user=xxx
2017/12/20 17:04:17 Couldn't find config file in root directory. Creating config file...
2017/12/20 17:04:17 failed to create file in root directory: exec: "touch": executable file not found in %PATH%`

windows doesn't have `touch`

### PR DESCRIPTION
**Pull request by tylerdavisnordstrom**
Resolves #32

### CODE REVIEW

File: cmd/cli/main.go [hunk 1]
```diff
@@ -208,10 +208,21 @@ func (config *Config) aliasSearch(alias string) (*AliasConfig, bool) {
...
-		return errors.Wrap(err, "failed to create file in root directory")
+	// Does file exist? Update mtime, else create file
+	_, e := os.Stat(onDiskFile)
+	if os.IsNotExist(e) { // Create file
+		fh, err := os.Create(onDiskFile)
+		if err != nil {
+			return errors.Wrap(err, "failed to create file in root directory")
+		}
+		fh.Close()
+	} else { //File Exists
```
Comment (SleepyBrett) [inline cmd/cli/main.go]: Lets remove the else clause, we don't need it. The intent of the original code was to create the file if it didn't exists already.
